"""
    Init DB

Revision ID: 207c8ed632a2
Revises:
Create Date: 2023-01-16 02:31:48.706179

"""
from alembic import op
from sqlalchemy import INTEGER, VARCHAR, Column, ForeignKey, BOOLEAN, TEXT, DATETIME


# revision identifiers, used by Alembic.
revision = '207c8ed632a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
                    Column('id', INTEGER, primary_key=True),
                    Column('ovner', INTEGER, ForeignKey('user.id'), nullable=False),
                    Column('forward', BOOLEAN, unique=False, default=False, nullable=False),
                    Column('title', VARCHAR(256), default='', nullable=False),
                    Column('pub_date', DATETIME, default='CURRENT_TIMESTAMP'),
                    Column('last_modified', DATETIME, default='CURRENT_TIMESTAMP'),
                    Column('sity', VARCHAR(80), default='', nullable=False),
                    Column('content', TEXT, default='', nullable=False),
                    Column('typograf', TEXT, default='', nullable=False),
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
