version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: parserbot
    env_file:
      - .env
    volumes:
      - data:/app/data

volumes:
  sdata:
