version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: parserbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/app/data
    networks:
      - frontend

volumes:
  data:

networks:
  frontend:
    external:
      name: frontend
